valor = int(input())

print(valor)
print("{} nota(s) de R$ 100,00".format(int(valor / 100)))
notas = (valor % 100)
print("{} nota(s) de R$ 50,00".format(int(notas / 50)))
notas = (notas % 50)
print("{} nota(s) de R$ 20,00".format(int(notas / 20)))
notas = (notas % 20)
print("{} nota(s) de R$ 10,00".format(int(notas / 10)))
notas = (notas % 10)
print("{} nota(s) de R$ 5,00".format(int(notas / 5)))
notas = (notas % 5)
print("{} nota(s) de R$ 2,00".format(int(notas / 2)))
notas = (notas % 2)
print("{} nota(s) de R$ 1,00".format(int(notas / 1)))